import type { ElementType } from "react";
import {
  Anchor,
  Banknote,
  Compass,
  Cog,
  Fish,
  LifeBuoy,
  Package,
  Scale,
  Settings,
  Ship,
  Sofa,
  Truck,
  Waves,
  Wrench,
  Zap,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, ElementType> = {
  "Anchoring & Mooring": Anchor,
  "Boats & Vessels": Ship,
  "Cabin, Galley & Comfort": Sofa,
  "Covers & Accessories": Package,
  "Deck Hardware": Anchor,
  "Electrical & Power": Zap,
  "Electronics & Navigation": Compass,
  "Engines, Propulsion & Steering": Cog,
  "Finance, Insurance & Legal": Banknote,
  "Fishing & Harvesting": Fish,
  "Maintenance & Consumables": Wrench,
  "Plumbing, Pumps & Ventilation": Settings,
  "Safety, Security & Response": LifeBuoy,
  "Sailing: Rigging & Sails": Scale,
  "Trailers & Towing": Truck,
  Watersports: Waves,
};

export const SUBGROUP_ICONS: Record<string, ElementType> = {
  All: Package,
  Anchoring: Anchor,
  "Mooring & Docking": Anchor,
  "Leisure Boats": Ship,
  "Commercial Vessels": Ship,
  "Small Craft & Tenders": Ship,
  "Floating Assets": Ship,
  Galley: Sofa,
  Climate: Settings,
  Furniture: Sofa,
  "Covers & Shade": Package,
  Accessories: Package,
  Fittings: Anchor,
  "Rails & Stanchions": Anchor,
  "Hatches & Portlights": Package,
  "Batteries & Charging": Zap,
  "Power Generation": Zap,
  "Shore Power": Zap,
  Distribution: Zap,
  Lighting: Zap,
  Navigation: Compass,
  "Fishfinders & Sonar": Compass,
  Communications: Compass,
  Instruments: Compass,
  "Marine Cameras": Compass,
  Engines: Cog,
  "Propellers & Drivetrain": Cog,
  "Fuel, Cooling & Exhaust": Cog,
  "Controls & Instruments": Cog,
  "Engine Parts & Service": Wrench,
  "Steering & Manoeuvring": Cog,
  Services: Banknote,
  "Leisure Fishing": Fish,
  "Commercial Fishing": Fish,
  "Aquaculture & Harvesting": Fish,
  "Cleaning & Care": Wrench,
  "Paint & Antifouling": Wrench,
  Repair: Wrench,
  "Corrosion Protection": Wrench,
  "General Lubricants": Wrench,
  "Fresh Water": Settings,
  Sanitation: Settings,
  "Bilge & Washdown": Settings,
  "Hoses & Fittings": Settings,
  Ventilation: Settings,
  "Personal Safety": LifeBuoy,
  "Emergency & Survival": LifeBuoy,
  "Fire Safety": LifeBuoy,
  Security: LifeBuoy,
  Response: LifeBuoy,
  "Standing Rigging": Scale,
  "Running Rigging": Scale,
  Spars: Scale,
  "Furler Systems": Scale,
  Sails: Scale,
  "Sail Handling": Scale,
};

export function getCategoryIcon(name: string): ElementType {
  return CATEGORY_ICONS[name] ?? Package;
}

export function getSubgroupIcon(name: string): ElementType {
  return SUBGROUP_ICONS[name] ?? Package;
}

